### PR TITLE
Make computeGeometry public

### PR DESCRIPTION
**Pull request by SimonIT**
See #5

### CODE REVIEW

**Comment by SimonIT** [comment]
Is there anything against this change? @jeremyz

**Comment by jeremyz** [comment]
I would prefer to set it protected in Button and Menu as it should be ;)
I like to keep the API as closed as possible to avoid wrong usage or maintenance issues.
I don't get what your use case would be ?

**Comment by SimonIT** [comment]
In my box widget, I calculate the size based on the size of the children. And because the size of a label is calculated in computeGeometry, it must be calculated before my box widget, which is currently not the behavior. So I would call computeGeometry of the children in computeGeometry of my box method. And because I got a different package, I can not access the computeGeometry of the children

**Comment by jeremyz** [comment]
sure ... Menu works because it's in the same package, I always forget about that java thing.
when you have a nice and working Box widget, feel free to open a PR ;)

**Comment by SimonIT** [comment]
I will! I have already a very basic TextField. 

Can you add your formatting settings to the repo, so I don't have to make the formatting beforehand? This would be really nice

**Comment by SimonIT** [comment]
For the taintParent, how can I change it now? It's protected and has no setter or getter. So I have to make a subclass or what's you thought with this

**Comment by jeremyz** [comment]
haaa you want to actually use it, I thought we were just pretending ;) pushed.
I don't have any formatting settings, just vim.

**Comment by SimonIT** [comment]
Yes I wanna use it :D I wanna use everything for which I made a PR
Oh crap, you don't use an IDE? Isn't that annoying?

**Comment by jeremyz** [comment]
nope it isn't, I have autocompletion, that's enough for me,
and by the years, I can't type code with anything else but vim,
I'm so used to it, and efficient enough with code manipulation.

**Comment by SimonIT** [comment]
`taintParent` works by the way only, if I override
```java
@Override public void taint()
    {
        children.forEach( c -> c.taint() );
    }
```
from Assembly with the original from Element:
```java
public void taint()
    {
        this.tainted = true;
        if (parent != null && taintParent) parent.taint();
    }
```
Else I get this beautiful Stackoverflow:
```java
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.StackOverflowError
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:117)
	at de.nilsim.collapse.desktop.DesktopLauncher.main(DesktopLauncher.java:10)
Caused by: java.lang.StackOverflowError
	at ch.asynk.gdx.boardgame.ui.Assembly.taint(Assembly.java:50)
	at ch.asynk.gdx.boardgame.ui.Element.taint(Element.java:65)
	at ch.asynk.gdx.boardgame.ui.Assembly.lambda$taint$0(Assembly.java:50)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at ch.asynk.gdx.boardgame.ui.Assembly.taint(Assembly.java:50)
```

**Comment by SimonIT** [comment]
By the way, why is the taint() Method overridden in Assembly? I don't see any change in the test subproject with the default from Element @jeremyz

**Comment by jeremyz** [comment]
look at my coment in  #9. it's for window resizing.
I've just set a litte test, that taintParent stuff works if you set it properly, enable it only in the Elements that you will change and that are not owned by Root(Assembly).

**Comment by jeremyz** [comment]
http://cgit.asynk.ch/public/taintParent.patch

**Comment by SimonIT** [comment]
My purpose was to set taintParent on the children of my Box which is an assembly. Maybe a parameter taintChildren:boolean for the assembly taint method is a good way to call parent.taint(false). Or two seperate methods taint() which has the default behavior like element and taintChildren() which iterats over the children and calls taint()

**Comment by jeremyz** [comment]
yep, Assembly was not meant to be used as a building peace for widgets, but I can see why you're using it as such. I like your taintChildren idea. In it is !

**Pull request merged**
